// Auto-generated by scripts/sync-release-notes.js — do not edit manually.
// Source: RELEASE_NOTES.md

export const RELEASE_NOTES_MD = `# Release Notes — v0.5.4 (Stable)

## What's New

- Templates — save and reuse QR style configurations with one tap
- SVG vector export — infinite quality scaling for print and design
- What's New screen — shows changelog automatically on app updates
- Welcome screen — first-launch intro with app philosophy
- Support screen — Ko-fi, PayPal, and Gumroad links
- Smooth theme transitions — cross-fade without flash or flicker
- Logo shadow now off by default for cleaner look

## Fixes

- Theme transition flicker on both dev and production builds
- Template save button unresponsive inside ScrollView
- Toast z-index — now always renders above modals
- Last row border spacing in settings and info screens
- SVG export shared as document for WhatsApp/Signal/Telegram compatibility
- Nav bar text clipping removed
- Write permissions stripped from manifest`;
