// Auto-generated by scripts/sync-release-notes.js — do not edit manually.
// Source: RELEASE_NOTES.md

export const RELEASE_NOTES_MD = `# Release Notes — v0.5.0 (Stable)

## What's New

- QR generator with 8 payload types, 5 pixel styles, 3 eye styles, corner radius, and error correction levels
- Logo overlay with resize, reposition, border, and shadow controls
- QR scanner with camera and gallery support, torch toggle, barcode detection
- Scan any existing QR code to load it into the generator for customization
- Dynamic theme that syncs UI to your QR's background color
- Pure Black (AMOLED) mode for OLED screens
- History with search, swipe-to-delete, and clear all
- Export as PNG, share, copy content, or export as text file
- Randomize button to shuffle all colors and styles instantly

## Fixes

- Nav bar text clipping on Android
- Theme transition flash during navigation
- Logo position drift after style changes
- Removed microphone permission from manifest

## Notes

- Preview builds may be unpolished and contain bugs
- For stable use, wait for a \`v*\` release without pre-release label
- Android 7.0+ required`;
