import { EyeShape, PupilShape, PixelShape } from "../types/qr";

export const EYE_SHAPES: { id: EyeShape; label: string }[] = [
  { id: "sharp", label: "Sharp" },
  { id: "soft", label: "Soft" },
  { id: "round", label: "Round" },
  { id: "pill", label: "Pill" },
  { id: "dot", label: "Dot" },
  { id: "shield", label: "Shield" },
  { id: "hexagon", label: "Hex" },
  { id: "octagon", label: "Oct" },
];

export const PUPIL_SHAPES: { id: PupilShape; label: string }[] = [
  { id: "dot", label: "Dot" },
  { id: "square", label: "Square" },
  { id: "diamond", label: "Diamond" },
  { id: "cross", label: "Cross" },
  { id: "hexagon", label: "Hex" },
  { id: "octagon", label: "Oct" },
  { id: "shield", label: "Shield" },
  { id: "star", label: "Star" },
  { id: "heart", label: "Heart" },
  { id: "blob", label: "Blob" },
  { id: "dome", label: "Dome" },
  { id: "oval", label: "Oval" },
  { id: "pentagon", label: "Penta" },
  { id: "scallop", label: "Scallop" },
  { id: "cloud", label: "Cloud" },
  { id: "droplet", label: "Drop" },
];

export const PIXEL_SHAPES: { id: PixelShape; label: string }[] = [
  { id: "sharp", label: "Square" },
  { id: "soft", label: "Soft" },
  { id: "round", label: "Round" },
  { id: "dots", label: "Dots" },
  { id: "liquid", label: "Liquid" },
  { id: "glued", label: "Glued" },
  { id: "smooth", label: "Smooth" },
  { id: "flow", label: "Flow" },
  { id: "blob", label: "Blob" },
  { id: "diamond", label: "Diamond" },
  { id: "cross", label: "Cross" },
  { id: "star", label: "Star" },
  { id: "triangle", label: "Triangle" },
  { id: "hexagon", label: "Hex" },
  { id: "plus", label: "Plus" },
  { id: "heart", label: "Heart" },
  { id: "sparkle", label: "Sparkle" },
  { id: "chevron", label: "Chevron" },
  { id: "wave", label: "Wave" },
  { id: "pinched-square", label: "Pinch" },
  { id: "circuit-board", label: "Circuit" },
  { id: "hashtag", label: "Hash" },
  { id: "vertical-line", label: "V-Line" },
  { id: "horizontal-line", label: "H-Line" },
];
