import React from "react";
import type { IconProps } from "phosphor-react-native";
import {
  PlusCircleIcon,
  StackIcon,
  WarningCircleIcon,
  ApertureIcon,
  ArrowLeftIcon,
  BookmarkSimpleIcon,
  WrenchIcon,
  BugIcon,
  CalendarBlankIcon,
  PhoneIcon,
  CoffeeIcon,
  ChatCircleIcon,
  ClipboardTextIcon,
  CodeIcon,
  PaletteIcon,
  CopyIcon,
  CubeIcon,
  DownloadSimpleIcon,
  CircleIcon,
  EyeIcon,
  EyeSlashIcon,
  GlobeIcon,
  GridFourIcon,
  HeartIcon,
  ImageIcon,
  ImagesIcon,
  InfoIcon,
  KeyIcon,
  LinkIcon,
  GithubLogoIcon,
  PaypalLogoIcon,
  EnvelopeIcon,
  MegaphoneIcon,
  FirstAidIcon,
  ListIcon,
  MoonIcon,
  UserIcon,
  DeviceMobileIcon,
  PulseIcon,
  QrCodeIcon,
  RadioButtonIcon,
  MinusCircleIcon,
  ScanIcon,
  GearIcon,
  ShareNetworkIcon,
  ShareFatIcon,
  ShieldCheckIcon,
  ShuffleIcon,
  GaugeIcon,
  SparkleIcon,
  SquareIcon,
  SunIcon,
  ArrowsLeftRightIcon,
  TextTIcon,
  ClockIcon,
  TrashIcon,
  TrendUpIcon,
  SpeakerHighIcon,
  WarningIcon,
  WifiHighIcon,
  CheckIcon,
  CheckCircleIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretDownIcon,
  XIcon,
  ArrowRightIcon,
  CameraIcon,
  MagnifyingGlassIcon,
  ArrowClockwiseIcon,
  ArrowsOutIcon,
  ArrowSquareOutIcon,
  LockIcon,
  LightningIcon,
  PencilSimpleIcon,
  XCircleIcon,
  QuestionIcon,
  SquaresFourIcon,
  CropIcon,
  GitBranchIcon,
  GitCommitIcon,
  XLogoIcon,
  ShapesIcon,
} from "phosphor-react-native";

const ICON_MAP: Record<string, React.ComponentType<IconProps>> = {
  "add-circle-outline": PlusCircleIcon,
  "albums-outline": StackIcon,
  "alert-circle-outline": WarningCircleIcon,
  "aperture-outline": ApertureIcon,
  "arrow-back": ArrowLeftIcon,
  "arrow-forward": ArrowRightIcon,
  "bookmark-outline": BookmarkSimpleIcon,
  "build-outline": WrenchIcon,
  "bug-outline": BugIcon,
  "calendar-outline": CalendarBlankIcon,
  "call-outline": PhoneIcon,
  "cafe-outline": CoffeeIcon,
  "camera-outline": CameraIcon,
  "chatbubble-outline": ChatCircleIcon,
  "checkmark": CheckIcon,
  "checkmark-circle": CheckCircleIcon,
  "chevron-back": CaretLeftIcon,
  "chevron-forward": CaretRightIcon,
  "clipboard-outline": ClipboardTextIcon,
  "close": XIcon,
  "code-working-outline": CodeIcon,
  "color-filter-outline": PaletteIcon,
  "color-palette-outline": PaletteIcon,
  "copy-outline": CopyIcon,
  "cube-outline": CubeIcon,
  "download": DownloadSimpleIcon,
  "download-outline": DownloadSimpleIcon,
  "ellipse-outline": CircleIcon,
  "eye-outline": EyeIcon,
  "eye-off-outline": EyeSlashIcon,
  "globe-outline": GlobeIcon,
  "grid-outline": GridFourIcon,
  "heart": HeartIcon,
  "heart-outline": HeartIcon,
  "image-outline": ImageIcon,
  "images-outline": ImagesIcon,
  "information-circle-outline": InfoIcon,
  "key-outline": KeyIcon,
  "link-outline": LinkIcon,
  "logo-github": GithubLogoIcon,
  "logo-paypal": PaypalLogoIcon,
  "mail-outline": EnvelopeIcon,
  "megaphone-outline": MegaphoneIcon,
  "medkit-outline": FirstAidIcon,
  "menu": ListIcon,
  "moon-outline": MoonIcon,
  "open-outline": ArrowSquareOutIcon,
  "person-outline": UserIcon,
  "phone-portrait-outline": DeviceMobileIcon,
  "pulse-outline": PulseIcon,
  "qr-code-outline": QrCodeIcon,
  "radio-button-on-outline": RadioButtonIcon,
  "refresh-outline": ArrowClockwiseIcon,
  "remove-circle-outline": MinusCircleIcon,
  "resize-outline": ArrowsOutIcon,
  "scan-circle-outline": ScanIcon,
  "scan-outline": ScanIcon,
  "search-outline": MagnifyingGlassIcon,
  "settings-outline": GearIcon,
  "share-outline": ShareNetworkIcon,
  "share-social-outline": ShareFatIcon,
  "shield-checkmark-outline": ShieldCheckIcon,
  "shuffle": ShuffleIcon,
  "speedometer-outline": GaugeIcon,
  "sparkles-outline": SparkleIcon,
  "square-outline": SquareIcon,
  "sunny-outline": SunIcon,
  "swap-horizontal-outline": ArrowsLeftRightIcon,
  "text-outline": TextTIcon,
  "time-outline": ClockIcon,
  "trash-outline": TrashIcon,
  "trending-up-outline": TrendUpIcon,
  "volume-high-outline": SpeakerHighIcon,
  "warning-outline": WarningIcon,
  "wifi-outline": WifiHighIcon,
  "flash": LightningIcon,
  "flash-outline": LightningIcon,
  "create-outline": PencilSimpleIcon,
  "close-circle-outline": XCircleIcon,
  "list-outline": ListIcon,
  "chevron-down": CaretDownIcon,
  "help": QuestionIcon,
  "apps-outline": SquaresFourIcon,
  "close-circle": XCircleIcon,
  "crop-outline": CropIcon,
  "git-branch-outline": GitBranchIcon,
  "git-commit-outline": GitCommitIcon,
  "lock-closed-outline": LockIcon,
  "logo-x": XLogoIcon,
  "shapes-outline": ShapesIcon,
  "warning": WarningIcon,
};

export type IconName = keyof typeof ICON_MAP;

export function Icon({ name, size = 20, color, weight = "regular", style }: IconProps & { name: IconName }) {
  const Component = ICON_MAP[name];
  if (!Component) return null;
  return <Component size={size} color={color} weight={weight} style={style} />;
}
